// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');

(async function startCast() {
  console.log('Starting cast...')
  const driver = await new Builder().forBrowser('chrome').build();

  try {
    await driver.get("https://cast.thosewizards.com.au/?push=tzsp4rT&stereo&quality=0&webcam&videodevice=1&autostart")
    await driver.manage().window().setRect(1844, 1014)
    await driver.findElement(By.id("container-3")).click()
  } catch(err) {
    console.error('Something went wrong?');
    console.error(err);
    process.exit(1);
  }
})();
